package com.context_mcp.context_mcp.domain.enums;

/**
 * Material actions recorded in the audit log.
 */
public enum AuditAction {
    CHECKPOINT_EVALUATED,
    CHECKPOINT_CONFIRMED,
    CHECKPOINT_SUPPRESSED,
    MEMORY_CREATED,
    MEMORY_UPDATED,
    MEMORY_DELETED,
    MEMORY_PERMANENTLY_DELETED,
    MEMORY_SUPERSEDED,
    MEMORY_RETRIEVED,
    SUPPRESSION_CREATED,
    SUPPRESSION_EXPIRED,
    CONSOLIDATION_PROPOSED,
    CONSOLIDATION_APPLIED,
    ARTIFACT_INDEXED,
    ARTIFACT_LINKED,
    ARTIFACT_REMOVED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    EXPORT_GENERATED,
    SECRET_REDACTED,
    SEARCH_EXECUTED
}
